name: CICD

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
    JAVA_VERSION: 11

jobs:
  build:

    name: Building Owiin
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:

    # Slack notification
      - name: Slack notification 
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # github code checkout
      - name: Checkout Github code    
        uses: actions/checkout@v2

      # Setup Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

       # Maven Clean Package
      - name: Maven Clean Package
        run: mvn clean package
