name: CICD

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
    JAVA_VERSION: 11

jobs:
  build:

    name: Building Owiin
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          mvn clean install
